DISABLE TRIGGER tri_Update_SC ON SC;
SELECT * FROM SC WHERE SC.Sno = 'S1' AND SC.Cno = 'C2';
UPDATE SC SET SC.Score = 0 WHERE SC.Sno = 'S1' AND SC.Cno = 'C2';
SELECT * FROM SC WHERE SC.Sno = 'S1' AND SC.Cno = 'C2';